[2023-01-01T22:06:14.526-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: get_interactions.intact.download_files manual__2023-01-02T01:06:12.069428+00:00 [queued]>
[2023-01-01T22:06:14.539-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: get_interactions.intact.download_files manual__2023-01-02T01:06:12.069428+00:00 [queued]>
[2023-01-01T22:06:14.539-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T22:06:14.539-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-01T22:06:14.539-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T22:06:14.552-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): intact.download_files> on 2023-01-02 01:06:12.069428+00:00
[2023-01-01T22:06:14.557-0300] {standard_task_runner.py:55} INFO - Started process 23844 to run task
[2023-01-01T22:06:14.559-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_interactions', 'intact.download_files', 'manual__2023-01-02T01:06:12.069428+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/get_interactions.py', '--cfg-path', '/tmp/tmp0x4afov3']
[2023-01-01T22:06:14.560-0300] {standard_task_runner.py:83} INFO - Job 194: Subtask intact.download_files
[2023-01-01T22:06:14.627-0300] {task_command.py:389} INFO - Running <TaskInstance: get_interactions.intact.download_files manual__2023-01-02T01:06:12.069428+00:00 [running]> on host kallo-Ubuntu
[2023-01-01T22:06:14.706-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kallox
AIRFLOW_CTX_DAG_ID=get_interactions
AIRFLOW_CTX_TASK_ID=intact.download_files
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T01:06:12.069428+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-02T01:06:12.069428+00:00
[2023-01-01T22:06:15.972-0300] {logging_mixin.py:137} INFO - 0
[2023-01-01T22:06:17.081-0300] {logging_mixin.py:137} INFO - 1
[2023-01-01T22:07:17.139-0300] {logging_mixin.py:137} INFO - 2 inicia descanso
[2023-01-01T22:07:18.660-0300] {logging_mixin.py:137} INFO - 2
[2023-01-01T22:07:19.800-0300] {logging_mixin.py:137} INFO - 3
[2023-01-01T22:07:20.706-0300] {local_task_job.py:224} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-01-01T22:07:20.716-0300] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 23844. PIDs of all processes in the group: [23844]
[2023-01-01T22:07:20.716-0300] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 23844
[2023-01-01T22:07:20.717-0300] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-01T22:07:20.769-0300] {process_utils.py:79} INFO - Process psutil.Process(pid=23844, status='terminated', exitcode=0, started='22:06:14') (23844) terminated with exit code 0
