[2023-01-01T22:04:32.332-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: get_interactions.intact.download_files manual__2023-01-02T01:04:29.360794+00:00 [queued]>
[2023-01-01T22:04:32.345-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: get_interactions.intact.download_files manual__2023-01-02T01:04:29.360794+00:00 [queued]>
[2023-01-01T22:04:32.345-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T22:04:32.345-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-01T22:04:32.345-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T22:04:32.360-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): intact.download_files> on 2023-01-02 01:04:29.360794+00:00
[2023-01-01T22:04:32.364-0300] {standard_task_runner.py:55} INFO - Started process 23428 to run task
[2023-01-01T22:04:32.367-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_interactions', 'intact.download_files', 'manual__2023-01-02T01:04:29.360794+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/get_interactions.py', '--cfg-path', '/tmp/tmpyf72hs0e']
[2023-01-01T22:04:32.368-0300] {standard_task_runner.py:83} INFO - Job 189: Subtask intact.download_files
[2023-01-01T22:04:32.440-0300] {task_command.py:389} INFO - Running <TaskInstance: get_interactions.intact.download_files manual__2023-01-02T01:04:29.360794+00:00 [running]> on host kallo-Ubuntu
[2023-01-01T22:04:32.515-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kallox
AIRFLOW_CTX_DAG_ID=get_interactions
AIRFLOW_CTX_TASK_ID=intact.download_files
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T01:04:29.360794+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-02T01:04:29.360794+00:00
[2023-01-01T22:04:34.106-0300] {logging_mixin.py:137} INFO - 0
[2023-01-01T22:04:35.229-0300] {logging_mixin.py:137} INFO - 1
[2023-01-01T22:05:35.287-0300] {logging_mixin.py:137} INFO - 2 inicia descanso
[2023-01-01T22:05:36.868-0300] {logging_mixin.py:137} INFO - 2
[2023-01-01T22:05:38.006-0300] {logging_mixin.py:137} INFO - 3
[2023-01-01T22:06:14.112-0300] {local_task_job.py:224} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-01-01T22:06:14.121-0300] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 23428. PIDs of all processes in the group: [23428]
[2023-01-01T22:06:14.121-0300] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 23428
[2023-01-01T22:06:14.121-0300] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-01T22:06:14.173-0300] {process_utils.py:79} INFO - Process psutil.Process(pid=23428, status='terminated', exitcode=0, started='22:04:31') (23428) terminated with exit code 0
