[2022-12-14T21:27:18.661-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_uniprot.download_files manual__2022-12-15T00:27:17.532063+00:00 [queued]>
[2022-12-14T21:27:18.673-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_uniprot.download_files manual__2022-12-15T00:27:17.532063+00:00 [queued]>
[2022-12-14T21:27:18.673-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T21:27:18.674-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-14T21:27:18.674-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T21:27:18.687-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): download_files> on 2022-12-15 00:27:17.532063+00:00
[2022-12-14T21:27:18.691-0300] {standard_task_runner.py:55} INFO - Started process 131190 to run task
[2022-12-14T21:27:18.694-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_uniprot', 'download_files', 'manual__2022-12-15T00:27:17.532063+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/download_uniprot.py', '--cfg-path', '/tmp/tmpak5r9yhi']
[2022-12-14T21:27:18.694-0300] {standard_task_runner.py:83} INFO - Job 13: Subtask download_files
[2022-12-14T21:27:18.765-0300] {task_command.py:389} INFO - Running <TaskInstance: download_uniprot.download_files manual__2022-12-15T00:27:17.532063+00:00 [running]> on host kallo-Ubuntu
[2022-12-14T21:27:18.843-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kallox
AIRFLOW_CTX_DAG_ID=download_uniprot
AIRFLOW_CTX_TASK_ID=download_files
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T00:27:17.532063+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-15T00:27:17.532063+00:00
[2022-12-14T21:27:18.843-0300] {logging_mixin.py:137} INFO - /home/kallox/***/dags
[2022-12-14T21:27:47.901-0300] {logging_mixin.py:137} INFO - antibody downloaded.
[2022-12-14T21:27:48.120-0300] {logging_mixin.py:137} INFO - antibody.json saved.
[2022-12-14T21:28:34.733-0300] {local_task_job.py:224} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-12-14T21:28:34.740-0300] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 131190. PIDs of all processes in the group: [131190]
[2022-12-14T21:28:34.741-0300] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 131190
[2022-12-14T21:28:34.741-0300] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-12-14T21:28:34.793-0300] {process_utils.py:79} INFO - Process psutil.Process(pid=131190, status='terminated', exitcode=0, started='21:27:17') (131190) terminated with exit code 0
